import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime, timedelta

st.set_page_config(layout="wide", page_title="TradeSignal Pro")

try:
   from alpaca.trading.client import TradingClient
   from alpaca.trading.requests import MarketOrderRequest, GetOrdersRequest
   from alpaca.trading.enums import OrderSide, TimeInForce, QueryOrderStatus
   ALPACA_AVAILABLE = True
except ImportError:
   ALPACA_AVAILABLE = False

DEFAULT_US = [
   # Mega Cap Tech
   "AAPL","MSFT","NVDA","GOOGL","GOOG","META","AMZN","TSLA","AMD","NFLX",
   # Financials
   "JPM","MS","GS","BAC","WFC","C","BLK","AXP","V","MA","PYPL",
   # Healthcare
   "JNJ","UNH","PFE","ABBV","MRK","LLY","TMO","ABT","CVS","AMGN",
   # Energy
   "XOM","CVX","COP","SLB","EOG","MPC","PSX","VLO","OXY","HAL",
   # Consumer
   "WMT","HD","MCD","NKE","SBUX","TGT","COST","LOW","TJX",
   # Industrials
   "BA","CAT","HON","UPS","RTX","LMT","GE","MMM","DE","FDX",
   # Communication & Media
   "DIS","CMCSA","T","VZ","CHTR","TMUS","SNAP","PINS","UBER","LYFT",
   # Semiconductors
   "INTC","QCOM","AVGO","TXN","MU","AMAT","LRCX","KLAC","MRVL","SMCI",
   # Cloud & Software
   "CRM","ORCL","ADBE","NOW","SNOW","PLTR","DDOG","ZS","NET","CRWD",
   # ETFs & Index
   "SPY","QQQ","IWM","DIA","XLK","XLF","XLE","XLV","XLI","ARKK",
]
DEFAULT_US = list(dict.fromkeys(DEFAULT_US))

DEFAULT_IN_50 = [
   "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
   "WIPRO.NS","BAJFINANCE.NS","SBIN.NS","LT.NS","TATAMOTORS.NS",
   "HINDUNILVR.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS","TITAN.NS",
   "ULTRACEMCO.NS","NESTLEIND.NS","POWERGRID.NS","NTPC.NS","ONGC.NS",
   "COALINDIA.NS","HCLTECH.NS","TECHM.NS","AXISBANK.NS","KOTAKBANK.NS",
   "INDUSINDBK.NS","BHARTIARTL.NS","ITC.NS","DRREDDY.NS","CIPLA.NS",
   "DIVISLAB.NS","EICHERMOT.NS","HEROMOTOCO.NS","BAJAJ-AUTO.NS","BPCL.NS",
   "GRASIM.NS","HINDALCO.NS","JSWSTEEL.NS","TATASTEEL.NS","TATACONSUM.NS",
   "UPL.NS","APOLLOHOSP.NS","ADANIENT.NS","ADANIGREEN.NS","ADANIPORTS.NS",
   "BAJAJFINSV.NS","BRITANNIA.NS","SBILIFE.NS","HDFCLIFE.NS","M&M.NS",
]

DEFAULT_IN = DEFAULT_IN_50 + [
   # Nifty Next 50
   "AMBUJACEM.NS","AUROPHARMA.NS","BANDHANBNK.NS","BERGEPAINT.NS","BEL.NS",
   "BOSCHLTD.NS","CANBK.NS","CHOLAFIN.NS","COLPAL.NS","DABUR.NS",
   "DLF.NS","GAIL.NS","GODREJCP.NS","HAVELLS.NS","HINDPETRO.NS",
   "ICICIGI.NS","ICICIPRULI.NS","INDUSTOWER.NS","IRCTC.NS","JUBLFOOD.NS",
   "LICHSGFIN.NS","LUPIN.NS","MARICO.NS","MCDOWELL-N.NS","MUTHOOTFIN.NS",
   "NAUKRI.NS","NMDC.NS","OFSS.NS","PAGEIND.NS","PIDILITIND.NS",
   "PNB.NS","RECLTD.NS","SAIL.NS","SHREECEM.NS","SIEMENS.NS",
   "SRF.NS","TORNTPHARM.NS","TRENT.NS","VEDL.NS","VOLTAS.NS",
   "ZOMATO.NS","DMART.NS","PIIND.NS","ALKEM.NS","BALKRISIND.NS",
   "BIOCON.NS","CONCOR.NS","INDIGO.NS","MFSL.NS","MOTHERSON.NS",
   # Nifty Midcap 100
   "ABCAPITAL.NS","ABFRL.NS","AJANTPHARM.NS","APOLLOTYRE.NS","ASHOKLEY.NS",
   "ASTRAL.NS","ATUL.NS","AUBANK.NS","BAJAJHLDNG.NS",
   "BATAINDIA.NS","BHEL.NS","BLUEDART.NS","CEATLTD.NS","CROMPTON.NS",
   "CUMMINSIND.NS","CYIENT.NS","DEEPAKNTR.NS","DIXON.NS","ELGIEQUIP.NS",
   "ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","FLUOROCHEM.NS",
   "GLENMARK.NS","GMRINFRA.NS","GNFC.NS","GODREJPROP.NS","GRANULES.NS",
   "GSPL.NS","GUJGASLTD.NS","HAL.NS","HFCL.NS","HONAUT.NS",
   "IDFCFIRSTB.NS","IEX.NS","INDHOTEL.NS","INDIANB.NS",
   "JKCEMENT.NS","JSL.NS","JUBLINGREA.NS","KAJARIACER.NS","KANSAINER.NS",
   "KEC.NS","LALPATHLAB.NS","LAURUSLABS.NS","LTTS.NS",
   "LUXIND.NS","MANAPPURAM.NS","MAXHEALTH.NS","MCX.NS",
   "METROPOLIS.NS","MRF.NS","NATCOPHARM.NS",
   "NAVINFLUOR.NS","NBCC.NS","NLCINDIA.NS","OBEROIRLTY.NS",
   "PERSISTENT.NS","PETRONET.NS","PFIZER.NS","PHOENIXLTD.NS","POLYCAB.NS",
   "PRAJIND.NS","PTC.NS","RAMCOCEM.NS",
   "RVNL.NS","SBICARD.NS","SCHAEFFLER.NS","SKFINDIA.NS","SOBHA.NS",
   "SONACOMS.NS","STARHEALTH.NS","SUMICHEM.NS","SUNDARMFIN.NS","SUNDRMFAST.NS",
   "SUPREMEIND.NS","SYNGENE.NS","TATACHEM.NS","TATACOMM.NS","TATAELXSI.NS",
   "TATAPOWER.NS","THERMAX.NS","TIMKEN.NS","TTKPRESTIG.NS",
   "TVSMOTOR.NS","UBLLTD.NS","UNIONBANK.NS",
   "VBL.NS","WHIRLPOOL.NS","ZEEL.NS","ZYDUSLIFE.NS",
]

DEFAULT_CR = ["BTC-USD","ETH-USD","SOL-USD","BNB-USD","XRP-USD","ADA-USD","DOGE-USD"]
DEFAULT_CM = ["GC=F","SI=F","CL=F","NG=F","HG=F","PL=F"]
COMMODITY_NAMES = {"GC=F":"Gold","SI=F":"Silver","CL=F":"Crude Oil","NG=F":"Natural Gas","HG=F":"Copper","PL=F":"Platinum"}

STRATEGIES = [
   "Triple SMA Ribbon (20/50/200)",
   "LuxAlgo ATR Channel",
   "MACD Momentum",
   "EMA 9/21 Ribbon",
   "Smart Money Concepts (SMC)",
   "Supertrend",
   "VWAP + RSI",
   "Ichimoku Cloud",
]

STRATEGY_TF
