yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as ob

# --- 1. APP CONFIGURATION & UI SETUP ---
st.set_page_config(layout="wide", page_title="Global Multi-Market Backtester")
st.title("📈 Global Multi-Market Strategy Dashboard")
st.markdown("Track live trends, generate buy/sell action conditions, and run instantly simulated backtests across US & Indian Stock Markets.")

# --- 2. SIDEBAR PARAMETERS ---
st.sidebar.header("⚙️ Strategy Parameters")

# Market Selection
market_type = st.sidebar.selectbox("Select Target Market", ["US Markets", "Indian Markets (NSE)"])

# Dynamically populate stock choices based on market
if market_type == "US Markets":
    default_tickers = ["AAPL", "NVDA", "MSFT", "TSLA", "AMD"]
    currency = "USD"
else:
    default_tickers = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "NIFTYBEES.NS"]
    currency = "INR"

selected_tickers = st.sidebar.multiselect("Choose Assets to Analyze", default_tickers, default=default_tickers[:3])

# Capital allocation and historical timeline inputs
initial_capital = st.sidebar.number_input("Starting Capital per Asset", min_value=1000, value=10000, step=1000)
start_date = st.sidebar.date_input("Backtest Start Date", pd.to_datetime("2023-01-01"))
end_date = st.sidebar.date_input("Backtest End Date", pd.to_datetime("2026-05-15"))

# --- 3. THE ANALYTICS & BACKTESTING ENGINE ---
def run_analytics(tickers, start, end, capital):
    summary_data = []
    detailed_dfs = {}
    
    for ticker in tickers:
        try:
            df = yf.download(ticker, start=start, end=end, progress=False)
            if df.empty or len(df) < 200:
                continue
            
            # Flatten multi-index columns if generated by yfinance
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)
                
            # Compute Moving Averages
            df['SMA_20'] = df['Close'].rolling(window=20).mean()
            df['SMA_50'] = df['Close'].rolling(window=50).mean()
            df['SMA_200'] = df['Close'].rolling(window=200).mean()
            
            # Formulate the Signal Conditions
            df['Signal'] = 0
            buy_condition = (df['SMA_20'] > df['SMA_50']) & (df['SMA_50'] > df['SMA_200'])
            sell_condition = (df['SMA_20'] < df['SMA_50']) | (df['Close'] < df['SMA_200'])
            
            df['Signal'] = np.where(buy_condition, 1, np.where(sell_condition, -1, 0))
            df['Signal'] = df['Signal'].replace(0, np.nan).ffill().fillna(-1)
            
            # Calculate Strategy vs Asset Returns
            df['Asset_Return'] = df['Close'].pct_change()
            df['Strategy_Return'] = df['Asset_Return'] * df['Signal'].shift(1)
            
            cumulative_strat = (1 + df['Strategy_Return'].fillna(0)).cumprod()
            cumulative_bh = (1 + df['Asset_Return'].fillna(0)).cumprod()
            
            final_strat_pct = (cumulative_strat.iloc[-1] - 1) * 100
            final_bh_pct = (cumulative_bh.iloc[-1] - 1) * 100
            ending_val = capital * cumulative_strat.iloc[-1]
            
            latest_sig = df['Signal'].iloc[-1]
            status = "🟢 BUY" if latest_sig == 1 else "🔴 SELL / AVOID"
            
            summary_data.append({
                "Ticker": ticker,
                "Current Price": round(df['Close'].iloc[-1], 2),
                "Live Condition": status,
                "Strategy Return (%)": round(final_strat_pct, 2),
                "Ending Value": f"{round(ending_val, 2)} {currency}",
                "Buy & Hold (%)": round(final_bh_pct, 2)
            })
            
            detailed_dfs[ticker] = df
            
        except Exception as e:
            st.error(f"Error compiling data for {ticker}: {e}")
            
    return pd.DataFrame(summary_data), detailed_dfs

# --- 4. RENDER PLATFORM VIEWPORT ---
if selected_tickers:
    summary_df, asset_charts = run_analytics(selected_tickers, start_date, end_date, initial_capital)
    
    # Section A: The Live Overview Table
    st.subheader("📊 Live Strategy Screener Matrix")
    st.dataframe(summary_df, use_container_width=True, hide_index=True)
    
    st.markdown("---")
    
    # Section B: Visual Chart Deep Dive
    st.subheader("🔍 Technical Chart & History Workspace")
    active_tab_ticker = st.selectbox("Select an asset to view its moving average chart structure:", selected_tickers)
    
    if active_tab_ticker in asset_charts:
        plot_df = asset_charts[active_tab_ticker]
        
        # Build interactive charting using Plotly
        fig = ob.Figure()
        fig.add_trace(ob.Scatter(x=plot_df.index, y=plot_df['Close'], name='Stock Price', line=dict(color='white', width=1.5)))
        fig.add_trace(ob.Scatter(x=plot_df.index, y=plot_df['SMA_20'], name='20 SMA (Fast)', line=dict(color='cyan', width=1)))
        fig.add_trace(ob.Scatter(x=plot_df.index, y=plot_df['SMA_50'], name='50 SMA (Medium)', line=dict(color='gold', width=1)))
        fig.add_trace(ob.Scatter(x=plot_df.index, y=plot_df['SMA_200'], name='200 SMA (Macro)', line=dict(color='magenta', width=1.5)))
        
        fig.update_layout(
            title=f"{active_tab_ticker} Technical Layout",
            template="plotly_dark",
            xaxis_title="Timeline",
            yaxis_title=f"Price ({currency})",
            height=550,
            margin=dict(l=20, r=20, t=40, b=20)
        )
        
